### ISSUE TITLE
Asset Unknowns

### ISSUE THREAD

**Issue by aers** [Caraxi/ULD#1]
Unk1 is an icon ID. If its not null/0, the game loads the icon instead of using the filename.
Unk2 is flags stating whether the texture is available in UI themes. I don't remember the exact specifics but it's just 1 bit per theme.

**Comment by aers** [comment]
Also a note for completeness:

The theme field only exists in version 101+ assets, not in 100, which was the version pre-theme. But there shouldn't be any old ULDs leftover(?) so it doesn't matter that much.

**Comment by Caraxi** [comment]
Ty.
There is 4 ULDs in the game that use Asset version 0100,
`ui/uld/ConfigLog.uld`
`ui/uld/iconVerminion.uld`
`ui/uld/JobHudARC0.uld`
`ui/uld/PvPCalender.uld`
